use_frameworks!

platform :ios, '8.0'

target 'ZCTableViewAnimationKit_Example' do
  pod 'ZCTableViewAnimationKit', :path => '../'

  target 'ZCTableViewAnimationKit_Tests' do
    inherit! :search_paths

    
  end
end
